/**
 * Regenerate `src/abap_cli/output/cli-output.schema.json` from the two TS
 * source-of-truth files:
 *   - `src/abap_cli/output/error-codes.ts`  → error.code enum, category mapping
 *   - `src/abap_cli/output/exit-codes.ts`   → exit-code table
 *
 * Only the dynamic parts (error.code enum + error.category enum) are derived;
 * the rest of the schema (top-level oneOf, meta, error object shape,
 * extensionMeta) is hand-written in the static template and verified against
 * the generated output. Run `npm run build-schema` after editing either
 * source-of-truth file.
 */
import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');
const schemaPath = path.join(repoRoot, 'src/abap_cli/output/cli-output.schema.json');
const errorCodesPath = path.join(repoRoot, 'src/abap_cli/output/error-codes.ts');
const exitCodesPath = path.join(repoRoot, 'src/abap_cli/output/exit-codes.ts');

/** Read a TS file and extract the union types / const records via regex.
 *  Lightweight: doesn't depend on a TS compiler — good enough for narrow extraction. */
function readFile(p: string): Promise<string> {
  return fs.readFile(p, 'utf-8');
}

/** Extract every TS string-literal from a `type X = 'A' | 'B' | 'C'` union. */
function extractUnionLiterals(src: string, name: string): string[] {
  const re = new RegExp(`export\\s+type\\s+${name}\\s*=\\s*([\\s\\S]*?);`);
  const m = re.exec(src);
  if (!m || !m[1]) throw new Error(`Could not find type ${name} in source`);
  return Array.from(m[1].matchAll(/'([A-Z][A-Z0-9_]*)'/g)).map((mm) => mm[1]!);
}

/** Extract const record literal from `export const FOO: Record<...> = { A: 1, B: 2 }`.
 *  Returns the literal keys with their numeric value (e.g. `["UNKNOWN", 1]`).
 *  Brace-balanced scan (regex is too brittle for nested braces). */
function extractRecordEntries(src: string, name: string): Array<[string, number]> {
  const declRe = new RegExp(`export\\s+const\\s+${name}\\b`);
  const m = declRe.exec(src);
  if (!m) throw new Error(`Could not find const ${name} declaration`);
  let i = src.indexOf('{', m.index);
  if (i < 0) throw new Error(`Could not find '{' for ${name}`);
  let depth = 1;
  const start = i + 1;
  for (i = i + 1; i < src.length && depth > 0; i++) {
    const ch = src[i];
    if (ch === '{') depth++;
    else if (ch === '}') depth--;
  }
  if (depth !== 0) throw new Error(`Unbalanced braces for ${name}`);
  const body = src.slice(start, i - 1);
  return Array.from(body.matchAll(/\b([A-Z][A-Z0-9_]*)\s*:\s*(\d+)/g)).map((mm) => [mm[1]!, Number(mm[2])] as [string, number]);
}

async function main(): Promise<void> {
  const [errorSrc, exitSrc, schemaRaw] = await Promise.all([
    readFile(errorCodesPath),
    readFile(exitCodesPath),
    readFile(schemaPath),
  ]);

  const errorCodes = extractUnionLiterals(errorSrc, 'ErrorCode');
  const categories = extractUnionLiterals(errorSrc, 'ErrorCategory');
  const exitCodes = extractRecordEntries(exitSrc, 'EXIT_CODES');

  if (errorCodes.length === 0) throw new Error('No ErrorCode union members extracted');
  if (categories.length === 0) throw new Error('No ErrorCategory union members extracted');
  if (exitCodes.length === 0) throw new Error('No EXIT_CODES entries extracted');

  const schema = JSON.parse(schemaRaw) as Record<string, unknown> & {
    definitions: Record<string, { description?: string; properties?: Record<string, Record<string, unknown>> }>;
  };
  const errorDef = schema.definitions.error;
  if (!errorDef) throw new Error('definitions.error missing in schema');

  // Replace dynamic enums.
  const errorProps = errorDef.properties;
  if (!errorProps) throw new Error('definitions.error.properties missing');
  errorProps.code = {
    type: 'string',
    enum: errorCodes,
    description: 'Literal ErrorCode (output/error-codes.ts). Derived by scripts/build-cli-schema.ts.',
  };
  errorProps.category = {
    enum: categories,
    description: 'ErrorCategory; maps 1:1 to the exit code (output/exit-codes.ts). Derived by scripts/build-cli-schema.ts.',
  };

  // Add a generated banner to definitions.error.description.
  errorDef.description =
    'Structured failure. `code` is the literal ErrorCode; `category` drives the exit code. ' +
    'Derived enums are regenerated by `npm run build-schema`. ' +
    'Extension failures always use dedicated EXTENSION_* codes and never override built-in codes.';

  // Append a generated annex with the exit-code table (informational, not enforced).
  (schema.definitions as Record<string, unknown>).__exitCodesAnnex = {
    type: 'object',
    description: 'Informational annex: category → exit code mapping (output/exit-codes.ts). Regenerated by scripts/build-cli-schema.ts.',
    properties: Object.fromEntries(exitCodes.map(([cat, code]) => [cat, { type: 'number', const: code }])),
    additionalProperties: false,
  };

  const next = JSON.stringify(schema, null, 2) + '\n';
  if (next === schemaRaw) {
    console.log(`[build-cli-schema] up-to-date: ${errorCodes.length} codes, ${categories.length} categories, ${exitCodes.length} exit codes`);
    return;
  }

  await fs.writeFile(schemaPath, next, 'utf-8');
  console.log(`[build-cli-schema] regenerated ${schemaPath}`);
  console.log(`  - error.code enum: ${errorCodes.length} entries`);
  console.log(`  - error.category enum: ${categories.length} entries`);
  console.log(`  - exit-code annex: ${exitCodes.length} entries`);
}

// Entry point — supports both `tsx scripts/build-cli-schema.ts` and `node --import tsx ...`.
const isDirect = (() => {
  try {
    return pathToFileURL(process.argv[1] ?? '').href === import.meta.url;
  } catch {
    return false;
  }
})();

if (isDirect) {
  main().catch((err) => {
    console.error('[build-cli-schema] FAILED:', err);
    process.exit(1);
  });
}

export { main, extractUnionLiterals, extractRecordEntries };
