#!/usr/bin/env bash
# Regenerate the AFF fixture coverage matrix (spec 033 SC-005 / T033-068)
# and append it to wiki/coverage-matrix.md as a new section.
#
# Source: `npm run validate:aff --json test/fixtures/` — schema PASS/WARN/FAIL
# per file. Aggregated by AFF type (CLAS/INTF/PROG/FUGR/TABL/STRU/DOMA/DTEL/
# HTTP/TRAN/TTYP/MSAG/DDLS).
#
# Usage: bash scripts/build-aff-fixture-matrix.sh
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MATRIX="$ROOT/wiki/coverage-matrix.md"
JSON_FILE="$(mktemp)"
trap "rm -f $JSON_FILE" EXIT

cd "$ROOT"
node "$ROOT/dist/src/abap_cli/index.js" validate:aff --json test/fixtures/ \
  > "$JSON_FILE" 2>/dev/null || true

node -e "
const fs = require('node:fs');
const raw = fs.readFileSync('$JSON_FILE', 'utf8');
let env;
try { env = JSON.parse(raw); }
catch (e) {
  console.error('validate:aff did not return JSON; aborting.');
  process.exit(1);
}
const files = env.data?.files ?? env.files ?? [];
const byType = new Map();
for (const f of files) {
  if (!byType.has(f.type)) byType.set(f.type, { pass: 0, warn: 0, fail: 0, total: 0 });
  const slot = byType.get(f.type);
  slot.total++;
  if (f.status === 'pass') slot.pass++;
  else if (f.status === 'warn') slot.warn++;
  else slot.fail++;
}
const order = ['CLAS','INTF','PROG','FUGR','TABL','STRU','DOMA','DTEL','HTTP','TRAN','TTYP','MSAG','DDLS'];
const rows = order
  .filter(t => byType.has(t))
  .map(t => {
    const s = byType.get(t);
    return '| ' + t + ' | ' + s.total + ' | ' + s.pass + ' | ' + s.warn + ' | ' + s.fail + ' |';
  });
const ts = new Date().toISOString();
const section = [
  '',
  '## AFF Fixture Coverage (spec 033 SC-005)',
  '',
  '> Auto-generated by \`scripts/build-aff-fixture-matrix.sh\` from \`npm run validate:aff --json test/fixtures/\`.',
  '> Last run: ' + ts,
  '',
  'Per-type fixture-level schema validation. The matrix answers',
  '\`spec 033 SC-005\`: 10 supported types × ≥ 1 fixture × official schema.',
  '',
  '| Type | Fixtures | PASS | WARN | FAIL |',
  '|------|----------|------|------|------|',
  ...rows,
  '',
  '### Schema paths',
  '',
  '| Type | Schema file |',
  '|------|-------------|',
  '| CLAS | \`tmp/abap-file-formats/file-formats/clas/clas-v1.json\` |',
  '| INTF | \`tmp/abap-file-formats/file-formats/intf/intf-v1.json\` |',
  '| PROG | \`tmp/abap-file-formats/file-formats/prog/prog-v1.json\` |',
  '| FUGR | \`tmp/abap-file-formats/file-formats/fugr/fugr-v1.json\` |',
  '| TABL | \`tmp/abap-file-formats/file-formats/tabl/tabl-v1.json\` |',
  '| STRU | \`tmp/abap-file-formats/file-formats/tabl/tabl-v1.json\` (alias) |',
  '| DOMA | \`tmp/abap-file-formats/file-formats/doma/doma-v1.json\` |',
  '| DTEL | \`tmp/abap-file-formats/file-formats/dtel/dtel-v1.json\` |',
  '| HTTP | \`tmp/abap-file-formats/file-formats/http/http-v1.json\` |',
  '| TRAN | \`tmp/abap-file-formats/file-formats/tran/tran-v1.json\` |',
  '',
  'Companion files (TABL/STRU \`.settings.json\`) validate against \`tabt-v1.json\`.',
  'PROG and HTTP fixtures are handcrafted (upstream abap-file-format 0.5.0',
  'lacked examples at spec 033 cut-off).',
  '',
];

const target = '$MATRIX';
const existing = fs.readFileSync(target, 'utf8');
const sentinel = '## AFF Fixture Coverage (spec 033 SC-005)';
const idx = existing.indexOf(sentinel);
let out;
if (idx >= 0) {
  // Replace from sentinel onwards.
  out = existing.slice(0, idx).replace(/\n+$/, '\n') + section.join('\n');
} else {
  // Append before the trailing references block.
  const refIdx = existing.lastIndexOf('\n---\n\n# references');
  if (refIdx >= 0) {
    out = existing.slice(0, refIdx) + section.join('\n') + existing.slice(refIdx);
  } else {
    out = existing.replace(/\n+$/, '\n') + section.join('\n');
  }
}
fs.writeFileSync(target, out);
console.log('Wrote AFF fixture matrix section to ' + target + ' (' + files.length + ' files across ' + byType.size + ' types)');
"
